### ISSUE TITLE
能否添加批量选择元素功能？

### ISSUE THREAD

**Issue by user0650** [analysys/ans-javascript-sdk#1]
![image](https://user-images.githubusercontent.com/7190674/67929305-fb1d3500-fbf7-11e9-900e-145bd66703f4.png)

如图，需要圈选一批按钮，任意一个点击都作为「分类点击事件」，该事件会作为后续的漏斗分析、路径分析。

目前版本好像不支持，是否考虑添加此特性？

**Comment by analysyszhangyufei** [comment]
> ![image](https://user-images.githubusercontent.com/7190674/67929305-fb1d3500-fbf7-11e9-900e-145bd66703f4.png)
> 
> 如图，需要圈选一批按钮，任意一个点击都作为「分类点击事件」，该事件会作为后续的漏斗分析、路径分析。
> 
> 目前版本好像不支持，是否考虑添加此特性？

该功能目前已进入调研阶段。
