### ISSUE TITLE
埋点的同时进行页面跳转操作，导致埋点上传请求被 canceled

### ISSUE THREAD

**Issue by lazipy** [analysys/ans-javascript-sdk#2]
由于请求时跳转页面，导致请求链接被中断，所以上传失败。

eg: 
```
AnalysysAgent.track("", "");
window.location.href = "";
```

意见：
1. 是否考虑兼容 Promise 规范
2. 通过猴子补丁的方式管理异步，参考 zone.js

**Comment by analysyszhangyufei** [comment]
考虑到ie的兼容性，对于这种类型后期会使用回调的方式告知api使用者。日志上报状况的节点

**Comment by analysyszhangyufei** [comment]
> 由于请求时偏移页面，导致请求链接被中断，所以上传失败。
> 
> 例如：
> 
> ```
> AnalysysAgent.track("", "");
> window.location.href = "";
> ```
> 
> 意见：
> 
> 1. 是否考虑兼容Promise规范
> 2. 通过猴子补丁的方式管理异步，参考zone.js

考虑到ie的兼容性，对于这种类型后期会使用替代的方式来告知api用户。

**Comment by xmsz** [comment]
现在是怎么处理
