### ISSUE TITLE
是否支持多实例？

### ISSUE THREAD

**Issue by rainyjune** [analysys/ans-javascript-sdk#3]
Google analytics 支持创建多个 tracker，请问这个SDK支持吗？

https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers#working_with_multiple_trackers

**Comment by analysyszhangyufei** [comment]
目前不支持。

**Comment by larryisthere** [comment]
如果是想应对“这对由多名负责人分别管理各个版块的网站非常有用；每名负责人都可以查看自己的媒体资源。”类似的场景。可以通过在方舟(5.0及以上版本支持)内给事件加权限来解决。

针对事件权限，方舟支持如下设置：
1）按事件名称
2）按事件属性

没有某些事件权限的用户无法查看及使用这些事件，关注不同模块的人也就不会被不关心的数据打扰。
同时，更重要的是不用提升埋点的数量和复杂度。而减少代码埋点对产品的侵入（尤其针对 app）也是我们更提倡的。
